# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [16]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [17]:
weather_csv_file = "../WeatherPy/city_data.csv"

weather_df = pd.read_csv(weather_csv_file)

weather_df.head()

,Unnamed: 0,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,0,Tsimmerbude,54.6750,20.1347,42.85,91,85,7.29,RU,1650927993
1,1,Portland,45.5234,-122.6762,60.64,78,100,10.36,US,1650927634
2,2,Armidale,-30.5167,151.6500,54.25,81,100,7.83,AU,1650927993
3,3,Busselton,-33.6500,115.3333,62.91,60,98,16.55,AU,1650927723
4,4,Cabo San Lucas,22.8909,-109.9124,82.62,62,10,8.39,MX,1650927667

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [18]:
# Configure gmaps with API key.
gmaps.configure(api_key=g_key)

# Convert Humidity to float and store
# Also, handle NaN values
weather_df = weather_df.dropna()
humidity = weather_df["Humidity"].astype(float)

# Store 'Latitude' and 'Longitude' into  locations. 
locations = weather_df[["Lat", "Lng"]].astype(float)

# Create a humidity Heatmap layer
fig = gmaps.figure()

heat_layer = gmaps.heatmap_layer(locations, weights=humidity, 
                                 dissipating=False, max_intensity=max(weather_df["Humidity"]),
                                 point_radius = 2)

fig.add_layer(heat_layer)
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [19]:
# Narrow down the DataFrame to find your ideal weather condition.
filtered_weather_df = weather_df

# Drop any rows that don't contain all three conditions. Want to be sure the weather is ideal.

# A max temperature lower than 80 degrees but higher than 70.
filtered_weather_df = filtered_weather_df.loc[(filtered_weather_df["Max Temp"] < 80) & (filtered_weather_df["Max Temp"] > 70)]

# Wind speed less than 10 mph.
filtered_weather_df = filtered_weather_df.loc[filtered_weather_df["Wind Speed"] < 10]

# Zero cloudiness.
filtered_weather_df = filtered_weather_df.loc[filtered_weather_df["Cloudiness"] == 0]

# Drop any rows with null values
filtered_weather_df = filtered_weather_df.dropna()

filtered_weather_df

,Unnamed: 0,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
33,33,Cayenne,4.9333,-52.3333,79.09,1,0,0.00,GF,1650927609
35,35,Araouane,18.9048,-3.5265,78.89,20,0,9.37,ML,1650927999
55,55,Shibganj,24.6829,88.1598,79.81,76,0,8.72,BD,1650928001
82,82,South Valley,35.0101,-106.6781,71.82,14,0,1.28,US,1650928006
117,117,Chāndbāli,20.7833,86.7667,79.36,93,0,7.11,IN,1650928012
422,422,Saint-Pierre,-21.3393,55.4781,71.29,80,0,9.22,RE,1650927722
436,436,Tura,25.5198,90.2201,71.33,87,0,4.97,IN,1650927960
487,487,Taoudenni,22.6783,-3.9836,78.73,18,0,9.89,ML,1650928099

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [20]:
hotel_df = filtered_weather_df

# params dictionary to update each iteration
params = {
    "radius": 5000,
    "types": "lodging",
    "key": g_key
}

for index, row in hotel_df.iterrows():
    # get lat, lng from df
    lat = row["Lat"]
    lng = row["Lng"]

    # change location each iteration while leaving original params in place
    params["location"] = f"{lat},{lng}"
    
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # assemble url and make API request
    print(f"Retrieving Results for Index {index}: {row['City']}.")
    response = requests.get(base_url, params=params).json()
    
    # extract results
    results = response['results']
    
    try:
        print(f"Closest hotel is {results[0]['name']}.")
        hotel_df.loc[index, 'Hotel Name'] = results[0]['name']
        
    except (KeyError, IndexError):
        print("Missing field/result... skipping.")
        
    print("------------")

Retrieving Results for Index 33: Cayenne.
Closest hotel is Hôtel Le Dronmi.
------------
Retrieving Results for Index 35: Araouane.
Missing field/result... skipping.
------------
Retrieving Results for Index 55: Shibganj.
Closest hotel is Sajid vila.
------------
Retrieving Results for Index 82: South Valley.
Closest hotel is desert palms rv park.
------------
Retrieving Results for Index 117: Chāndbāli.
Closest hotel is KABITA HOMES.
------------
Retrieving Results for Index 422: Saint-Pierre.
Closest hotel is Lindsey Hôtel.
------------
Retrieving Results for Index 436: Tura.
Closest hotel is Hotel RIKMAN Continental.
------------
Retrieving Results for Index 487: Taoudenni.
Missing field/result... skipping.
------------

In [21]:
hotel_df

,Unnamed: 0,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Hotel Name
33,33,Cayenne,4.9333,-52.3333,79.09,1,0,0.00,GF,1650927609,Hôtel Le Dronmi
35,35,Araouane,18.9048,-3.5265,78.89,20,0,9.37,ML,1650927999,NaN
55,55,Shibganj,24.6829,88.1598,79.81,76,0,8.72,BD,1650928001,Sajid vila
82,82,South Valley,35.0101,-106.6781,71.82,14,0,1.28,US,1650928006,desert palms rv park
117,117,Chāndbāli,20.7833,86.7667,79.36,93,0,7.11,IN,1650928012,KABITA HOMES
422,422,Saint-Pierre,-21.3393,55.4781,71.29,80,0,9.22,RE,1650927722,Lindsey Hôtel
436,436,Tura,25.5198,90.2201,71.33,87,0,4.97,IN,1650927960,Hotel RIKMAN Continental
487,487,Taoudenni,22.6783,-3.9836,78.73,18,0,9.89,ML,1650928099,NaN

In [22]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [23]:
# Assign the marker layer to a variable
locations = hotel_df[["Lat", "Lng"]]
markers = gmaps.marker_layer(locations)

# Create hotel symbol layer
hotel_layer = gmaps.symbol_layer(locations,info_box_content=hotel_info)
# Add the layer to the map
fig.add_layer(markers)
fig.add_layer(hotel_layer)
fig

Figure(layout=FigureLayout(height='420px'))